name: Scheduled and Manual Workflow

on:
  schedule:
    - cron:  '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Run Go program
      run: go run main.go
      env:
        SPC_CDS: ${{ secrets.SPC_CDS }}
        SPC_U: ${{ secrets.SPC_U }}
        SPC_SC_UD: ${{ secrets.SPC_SC_UD }}
        SPC_SC_TK: ${{ secrets.SPC_SC_TK }}
        SPC_EC: ${{ secrets.SPC_EC }}
        PRODUCT_IDS: ${{ secrets.PRODUCT_IDS }}